version: "3.4"
services:
  panel_serve:
    image: pavics/workflow-tests:220502
    container_name: panel_serve
    ports:
    - 9092:9092
    volumes:
    - ../../test-panel-serve/test-notebooks:/notebook_dir/test-notebooks-ro:ro
    command: panel serve /notebook_dir/test-notebooks/test-panel-servable-workdir.ipynb --port 9092
    restart: always

  proxy:
    volumes:
    - ../../test-panel-serve/panel_serve/panel_serve.conf:/etc/nginx/conf.extra-service.d/panel_serve/panel_serve.conf:ro
