version: "3.4"
services:
  panel_serve:
    image: pavics/workflow-tests:220502
    container_name: panel_serve
    ports:
    - 5007:5007
    volumes:
    - ../../test-panel-serve/test-notebooks:/notebook_dir/test-notebooks-ro:ro
    command: panel serve --port=5007 --allow-websocket-origin=* /notebook_dir/test-notebooks/test-panel-servable-workdir.ipynb
    restart: always

  proxy:
    volumes:
    - ../../test-panel-serve/panel_serve/panel_serve.conf:/etc/nginx/conf.extra-service.d/panel_serve/panel_serve.conf:ro
