version: "3.4"
services:
  panel_serve:
    image: pavics/workflow-tests:220502
    container_name: panel_serve
    environments:
    - JUPYTER_TOKEN: tryme
    ports:
    - 5007:5007
    volumes:
    - ../../test-panel-serve/test-notebooks:/notebook_dir/test-notebooks-ro:ro
    command: jupyter lab --ip=0.0.0.0 --port=5007 --no-browser --ServerApp.base_url=/panel_serve/
    #    command: bash -c "panel serve --port=5007 --allow-websocket-origin=* /notebook_dir/test-notebooks-ro/test-panel-servable-workdir.ipynb"
    restart: always

  proxy:
    volumes:
    - ../../test-panel-serve/panel_serve/panel_serve.conf:/etc/nginx/conf.extra-service.d/panel_serve/panel_serve.conf:ro
